database_options: !Sqlite bughouse.db
secret_database_options: !Sqlite bughouse-private.db
auth_options: !Google
  callback_is_https: false
  client_id_source: !EnvVar GOOGLE_CLIENT_ID
  client_secret_source: !EnvVar GOOGLE_CLIENT_SECRET
session_options: !WithSessions
  secret: !Literal "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  expire_in:
    secs: 2592000  # 30 days
    nanos: 0
static_content_url_prefix: http://localhost:8080
allowed_origin: Any
