database_options: !Sqlite <DB-PATH>/bughouse.db
secret_database_options: !Sqlite <DB-PATH>/bughouse-secret.db
auth_options:
  callback_is_https: true
  google: !Some
    client_id_source: !Literal "<GOOGLE-CLIENT-ID>"
    client_secret_source: !File <SECRET-PATH>/google-client-secret
  lichess: !Some
    client_id_source: !Literal "bughouse.pro"
session_options: !WithSessions
  secret: !File <SECRET-PATH>/session-secret
  expire_in: 30d
static_content_url_prefix: ""
allowed_origin: !ThisSite https://bughouse.pro
check_git_version: true
max_starting_time: 1h
