#!/bin/bash

set -e

export RUST_BACKTRACE=1
export RUST_LOG=INFO
#export RUST_LOG_STYLE=always
cd "$BUGHOUSE_ROOT"
cargo build -r --package bughouse_console
./target/release/bughouse_console server --sqlite-db ~/bughouse.db --secret-sqlite-db ~/bughouse-secret.db --enable-sessions --auth Google --auth-callback-is-https |& tee -i ~/server_log/`date +%Y%m%d-%H%M%S`.txt
